name: npc-talk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - git+https://github.com/agentscope-ai/agentscope.git
      - fastapi>=0.115
      - uvicorn[standard]>=0.30
